In [1]:
# !pip install --upgrade gmaps

# Import the dependencies.
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [2]:
!pip install collections

ERROR: Could not find a version that satisfies the requirement collections (from versions: none)
ERROR: No matching distribution found for collections

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Upernavik,GL,2022-01-30 20:50:34,72.7868,-56.1549,-2.63,70,100,9.42
1,1,Batagay,RU,2022-01-30 20:45:20,67.6333,134.6333,-35.27,99,50,1.77
2,2,Husavik,IS,2022-01-30 20:49:33,66.0449,-17.3389,22.91,63,47,30.13
3,3,Panjab,AF,2022-01-30 20:54:31,34.3880,67.0233,13.50,99,97,0.81
4,4,Warri,NG,2022-01-30 20:54:31,5.5167,5.7500,76.10,62,32,3.56

In [4]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [5]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [12]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
4,4,Warri,NG,2022-01-30 20:54:31,5.5167,5.7500,76.10,62,32,3.56
11,11,Kapaa,US,2022-01-30 20:48:16,22.0752,-159.3190,78.12,66,20,3.00
14,14,Rikitea,PF,2022-01-30 20:48:35,-23.1203,-134.9692,76.33,69,100,4.56
16,16,Hilo,US,2022-01-30 20:51:43,19.7297,-155.0900,78.53,54,20,5.75
18,18,Touros,BR,2022-01-30 20:51:30,-5.1989,-35.4608,85.10,74,21,12.84
20,20,Arraial Do Cabo,BR,2022-01-30 20:48:20,-22.9661,-42.0278,82.36,74,40,4.61
21,21,Cabo San Lucas,MX,2022-01-30 20:46:20,22.8909,-109.9124,79.61,64,85,6.46
22,22,Eirunepe,BR,2022-01-30 20:54:35,-6.6603,-69.8736,88.95,50,98,4.90
23,23,Takoradi,GH,2022-01-30 20:54:35,4.8845,-1.7554,79.84,81,100,6.44
24,24,Jacqueville,CI,2022-01-30 20:54:36,5.2052,-4.4146,82.31,84,100,11.10

In [13]:
preferred_cities_df.notnull().sum()

City_ID       144
City          144
Country       144
Date          144
Lat           144
Lng           144
Max Temp      144
Humidity      144
Cloudiness    144
Wind Speed    144
dtype: int64

In [14]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
4             Warri      NG     76.10   5.5167    5.7500
11            Kapaa      US     78.12  22.0752 -159.3190
14          Rikitea      PF     76.33 -23.1203 -134.9692
16             Hilo      US     78.53  19.7297 -155.0900
18           Touros      BR     85.10  -5.1989  -35.4608
20  Arraial Do Cabo      BR     82.36 -22.9661  -42.0278
21   Cabo San Lucas      MX     79.61  22.8909 -109.9124
22         Eirunepe      BR     88.95  -6.6603  -69.8736
23         Takoradi      GH     79.84   4.8845   -1.7554
24      Jacqueville      CI     82.31   5.2052   -4.4146

In [15]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.

In [16]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
4,Warri,NG,76.10,5.5167,5.7500,BON Hotel Delta
11,Kapaa,US,78.12,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
14,Rikitea,PF,76.33,-23.1203,-134.9692,People ThankYou
16,Hilo,US,78.53,19.7297,-155.0900,Hilo Hawaiian Hotel
18,Touros,BR,85.10,-5.1989,-35.4608,INN NEW HORIZON
20,Arraial Do Cabo,BR,82.36,-22.9661,-42.0278,Pousada Porto Praia
21,Cabo San Lucas,MX,79.61,22.8909,-109.9124,Hotel Tesoro Los Cabos
22,Eirunepe,BR,88.95,-6.6603,-69.8736,Atrás de você
23,Takoradi,GH,79.84,4.8845,-1.7554,Raybow International Hotel
24,Jacqueville,CI,82.31,5.2052,-4.4146,Hotel Le Martin Pecheur

In [21]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)

# marker_locations = list(locations.to_records(index=False))

marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

AttributeError: module 'collections' has no attribute 'Iterable'

In [18]:
locations.reset_index(inplace=True, drop=True)
locations=locations[["Lat", "Lng"]]
locations

         Lat       Lng
0     5.5167    5.7500
1    22.0752 -159.3190
2   -23.1203 -134.9692
3    19.7297 -155.0900
4    -5.1989  -35.4608
..       ...       ...
139  11.2408  -74.1990
140  -6.8367  -79.9342
141   8.2833   -7.6833
142 -23.8650   35.3833
143 -14.9003   50.2788

[144 rows x 2 columns]

In [19]:
gmaps.__version__

'0.9.0'